import { Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "./components/shared/navbar/SideNavBar";
import Topnavbar from "./components/shared/navbar/Topnavbar";
import FilterProvider from "./provider/FilterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FilterProvider>
        <body className={`${inter.className} scrollbar-hidden `}>
          <main className="bg-[#F5F6F8] lg:p-5 flex relative">
            <SideNavBar />
            <section className="w-full">
              <Topnavbar />
              {children}
            </section>
          </main>
        </body>
      </FilterProvider>
    </html>
  );
}
